### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [mmotykiewicz/prj-rev-bwfs-dasmoto#2]
https://github.com/mmotykiewicz/prj-rev-bwfs-dasmoto/blob/master/Project%204%20-%20Dasmoto's%20Arts%20%26%20Crafts/index.html#L2-L37

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/34071575-f77d9174-e245-11e7-8c8a-e051df39f409.png">

**Comment by mmotykiewicz** [comment]
Good point. I never comment any of my code.
